# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='\u6807\u9898')),
                ('pwd', models.CharField(blank=True, default='', max_length=64, verbose_name='\u5bc6\u7801')),
                ('sex', models.IntegerField(choices=[(0, '\u672a\u5f55\u5165'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='\u624b\u673a\u53f7')),
                ('wx_name', models.CharField(blank=True, default='', max_length=128, verbose_name='\u5fae\u4fe1\u540d\u79f0')),
                ('bak_data', models.CharField(blank=True, default='', max_length=128, verbose_name='\u5907\u7528\u5b57\u6bb5')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(blank=True, default='', max_length=256, verbose_name='\u8bf4\u660e')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='\u6807\u9898')),
                ('pic_url', models.FileField(upload_to=b'E:\\pythonCode\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247')),
                ('video_url', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('desc', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u63cf\u8ff0')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('recommend', models.IntegerField(default=0, verbose_name='\u63a8\u8350')),
                ('keywords', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5173\u952e\u5b57(\u7528\u82f1\u6587\u72b6\u6001\u4e0b\u9017\u53f7\u5206\u9694)')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5')),
                ('tags', models.ManyToManyField(to='video_manager.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u89c2\u770b\u65f6\u95f4')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.People')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=-1, verbose_name='\u8bc4\u5206')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.People')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.Video')),
            ],
        ),
    ]
