# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0003_auto_20171118_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to=b'E:\\pythonCode\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='video_record',
            name='bak_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5'),
        ),
        migrations.AddField(
            model_name='video_score',
            name='bak_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5'),
        ),
        migrations.AddField(
            model_name='video_score',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='people',
            name='bak_data',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5'),
        ),
    ]
