# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0004_auto_20171120_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avg_point',
            field=models.FloatField(default=0, verbose_name='\u5e73\u5747\u5206'),
        ),
        migrations.AddField(
            model_name='video',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='\u64ad\u653e\u8bb0\u5f55'),
        ),
    ]
