# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0006_auto_20171127_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u59d3\u540d'),
        ),
    ]
