# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0013_auto_20171206_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u8bc4\u8bba')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5')),
                ('parent_comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_manager.Video_Comment')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.People')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='video_score',
            name='comment',
        ),
        migrations.AddField(
            model_name='video_score',
            name='good',
            field=models.IntegerField(choices=[(0, '\u672a\u5f55\u5165'), (1, '\u8d5e'), (2, 'low')], default=0, verbose_name='\u70b9\u8d5e'),
        ),
    ]
