# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0014_auto_20171207_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_comment',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='video_comment',
            name='is_top',
            field=models.IntegerField(default=0, verbose_name='\u7f6e\u9876'),
        ),
    ]
