# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0015_auto_20171207_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xnjy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5b66\u6821')),
                ('jy', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5bc4\u8bed')),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u7559\u5b66\u65f6\u95f4')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.People')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to=b'E:\\pythonCode\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to=b'E:\\pythonCode\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247'),
        ),
    ]
