# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0017_xnjy_lx_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to=b'D:\\lxdzx\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to=b'D:\\lxdzx\\lxdzx_server/static/files/recv', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='xnjy',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u7559\u5b66\u65f6\u95f4(\u5907\u7528)'),
        ),
        migrations.AlterField(
            model_name='xnjy',
            name='lx_time',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u7559\u5b66\u65f6\u95f4'),
        ),
    ]
