# Generated by Django 2.2.2 on 2019-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0018_auto_20180404_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to='../static/files/recv', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pic_url',
            field=models.FileField(blank=True, default='', upload_to='../static/files/recv', verbose_name='图片'),
        ),
    ]
