# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='\u59d3\u540d')),
                ('zf', models.CharField(default='', max_length=128, verbose_name='\u795d\u798f')),
                ('bak_data', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5907\u7528\u5b57\u6bb5')),
            ],
        ),
    ]
