# Generated by Django 2.2.2 on 2019-06-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dzdptype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dzdp.DzdpType'),
        ),
    ]
