# Generated by Django 2.2.2 on 2019-06-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0002_dzdptype_parent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dzdpshop',
            old_name='type_name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='dzdpshop',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dzdp.DzdpCity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dzdpcity',
            name='bak',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='备份'),
        ),
        migrations.AlterField(
            model_name='dzdpcity',
            name='country',
            field=models.CharField(max_length=1023, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='dzdpshop',
            name='bak',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='备份'),
        ),
        migrations.AlterField(
            model_name='dzdptype',
            name='bak',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='备份'),
        ),
    ]
