# Generated by Django 2.2.2 on 2019-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0003_auto_20190617_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='dzdpcity',
            name='is_need',
            field=models.BooleanField(default=False, verbose_name='是否需要获取'),
        ),
    ]
