# Generated by Django 2.2.2 on 2019-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0004_dzdpcity_is_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='dzdptype',
            name='tag',
            field=models.CharField(default='', max_length=1023, verbose_name='标签'),
            preserve_default=False,
        ),
    ]
