# Generated by Django 2.2.2 on 2019-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0005_dzdptype_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dzdptype',
            name='is_need',
            field=models.BooleanField(default=False, verbose_name='是否需要获取'),
        ),
    ]
