# Generated by Django 2.2.2 on 2019-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0006_dzdptype_is_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dzdpcity',
            name='country',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='dzdpcity',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='dzdpcity',
            name='province',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='dzdpcity',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='dzdpshop',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='dzdpshop',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='dzdptype',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='dzdptype',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='标签'),
        ),
    ]
