# Generated by Django 2.2.3 on 2019-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzdp', '0010_dzdpshoptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dzdpshop',
            name='lastGetTime',
            field=models.DateTimeField(auto_now=True, verbose_name='上次爬取时间'),
        ),
    ]
