# Generated by Django 2.2.3 on 2020-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnovInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='0', max_length=64, verbose_name='区域序号')),
                ('confirmedNum', models.IntegerField(default=0, verbose_name='确诊人数')),
                ('curesNum', models.IntegerField(default=0, verbose_name='治愈人数')),
                ('deathsNum', models.IntegerField(default=0, verbose_name='死亡人数')),
                ('maybeNum', models.IntegerField(default=0, verbose_name='疑似')),
                ('bak', models.CharField(max_length=1023, verbose_name='备份')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023, verbose_name='名称')),
                ('mid', models.CharField(default='0', max_length=64, verbose_name='本平台序号')),
                ('pid', models.CharField(default='0', max_length=64, verbose_name='父节点序号')),
                ('upd_time', models.CharField(default='2020-02-01', max_length=128, verbose_name='数据时间')),
                ('desc', models.CharField(max_length=1023, verbose_name='描述')),
                ('bak', models.CharField(max_length=1023, verbose_name='备份')),
            ],
        ),
    ]
