# Generated by Django 3.0.2 on 2020-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncov', '0003_cnovhisinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnovhisinfo',
            name='upd_time',
            field=models.CharField(default='2020-02-01', max_length=128, verbose_name='数据时间'),
        ),
        migrations.AddField(
            model_name='cnovinfo',
            name='upd_time',
            field=models.CharField(default='2020-02-01', max_length=128, verbose_name='数据时间'),
        ),
    ]
