# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
                ('video_review', models.CharField(max_length=255)),
                ('favorites', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('play', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('typeid', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('aid', models.CharField(max_length=255)),
                ('mid', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('hide_click', models.CharField(max_length=255)),
                ('gl_title', models.CharField(max_length=255)),
                ('gl_url', models.CharField(max_length=255)),
            ],
        ),
    ]
