# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(default=0, verbose_name='\u5e73\u53f0')),
                ('clicks', models.IntegerField(default=0, verbose_name='\u603b\u70b9\u51fb\u91cf')),
                ('fans', models.IntegerField(default=0, verbose_name='\u603b\u7c89\u4e1d\u6570')),
                ('follows', models.IntegerField(default=0, verbose_name='\u5173\u6ce8\u6570')),
                ('plays', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u6570')),
                ('reads', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u6570')),
                ('title', models.CharField(max_length=1023, verbose_name='\u5907\u6ce8')),
            ],
        ),
    ]
