# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0004_platformstatistics_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformstatistics',
            name='get_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='platformstatistics',
            name='platform',
            field=models.IntegerField(choices=[(1, 'B\u7ad9'), (2, '\u4eca\u65e5\u5934\u6761')], default=0, verbose_name='\u5e73\u53f0'),
        ),
    ]
