# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0005_auto_20180905_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNameInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'B\u7ad9'), (2, '\u4eca\u65e5\u5934\u6761')], default=0, verbose_name='\u5e73\u53f0')),
                ('name', models.CharField(max_length=1023, verbose_name='\u540d\u79f0')),
                ('get_data', models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], default=0, verbose_name='\u5e73\u53f0')),
                ('desc', models.CharField(max_length=1023, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.RemoveField(
            model_name='platformstatistics',
            name='platform',
        ),
        migrations.AlterField(
            model_name='platformstatistics',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_web_data.VideoNameInfos'),
        ),
    ]
