# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0006_auto_20180905_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonameinfos',
            name='mid',
            field=models.CharField(default=0, max_length=1023, verbose_name='\u672c\u5e73\u53f0\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='videonameinfos',
            name='get_data',
            field=models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], default=0, verbose_name='\u662f\u5426\u722c\u866b'),
        ),
    ]
