# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0007_auto_20180905_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformstatistics',
            old_name='mid',
            new_name='vid',
        ),
    ]
