# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_web_data', '0011_videodetail_get_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='bak',
            field=models.CharField(max_length=1023, verbose_name='\u5907\u6ce8\u5185\u5bb9'),
        ),
    ]
